import type { Metadata } from "next";
import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import { business, serviceAreas } from "@/data/business";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-heading",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const SITE_URL = business.website;
const TITLE =
  "AL Mows Blocks | Mowing and Paddock Slashing | Copper Coast & Yorke Peninsula";
const DESCRIPTION =
  "Local mowing, block slashing and paddock slashing across Kadina, Moonta, Wallaroo, the Copper Coast and Yorke Peninsula. Contact AL Mows Blocks for a quote.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  applicationName: business.name,
  keywords: [
    "mowing",
    "block slashing",
    "paddock slashing",
    "Copper Coast",
    "Yorke Peninsula",
    "Kadina",
    "Moonta",
    "Wallaroo",
    "South Australia",
  ],
  alternates: {
    canonical: SITE_URL,
  },
  // The browser-tab favicon is generated by src/app/icon.tsx so it is always
  // valid. The Apple touch icon uses the supplied logo once it is in place.
  icons: {
    apple: "/images/al-mows-logo.png",
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: business.name,
    title: TITLE,
    description: DESCRIPTION,
    locale: "en_AU",
    images: [
      {
        url: "/images/al-mows-facebook-banner.png",
        width: 1200,
        height: 630,
        alt: `${business.name} — ${business.serviceDescription}`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    images: ["/images/al-mows-facebook-banner.png"],
  },
  robots: {
    index: true,
    follow: true,
  },
};

/**
 * LocalBusiness structured data. Uses only verifiable facts — no reviews,
 * ratings, prices, opening hours, street address or coordinates are invented.
 * Address is a PO Box (PostalAddress). areaServed is limited to the supplied
 * service locations.
 */
function LocalBusinessJsonLd() {
  const json = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "@id": `${SITE_URL}/#business`,
    name: business.name,
    description: DESCRIPTION,
    url: SITE_URL,
    telephone: "+61432225363",
    email: business.email,
    image: `${SITE_URL}/images/al-mows-logo.png`,
    address: {
      "@type": "PostalAddress",
      postOfficeBoxNumber: business.postalAddress.poBox,
      addressLocality: business.postalAddress.locality,
      addressRegion: business.postalAddress.region,
      postalCode: business.postalAddress.postcode,
      addressCountry: business.postalAddress.country,
    },
    areaServed: serviceAreas.locations.map((name) => ({
      "@type": "Place",
      name,
    })),
    sameAs: [business.facebook],
    identifier: {
      "@type": "PropertyValue",
      name: "ABN",
      value: business.abn,
    },
    makesOffer: [
      {
        "@type": "Offer",
        itemOffered: {
          "@type": "Service",
          name: "Block slashing",
          serviceType: "Block slashing",
          provider: { "@id": `${SITE_URL}/#business` },
          areaServed: serviceAreas.locations.map((name) => ({
            "@type": "Place",
            name,
          })),
        },
      },
      {
        "@type": "Offer",
        itemOffered: {
          "@type": "Service",
          name: "Paddock slashing",
          serviceType: "Paddock slashing",
          provider: { "@id": `${SITE_URL}/#business` },
          areaServed: serviceAreas.locations.map((name) => ({
            "@type": "Place",
            name,
          })),
        },
      },
    ],
  };

  return (
    <script
      type="application/ld+json"
      // JSON-LD is generated from trusted config, not user input.
      dangerouslySetInnerHTML={{ __html: JSON.stringify(json) }}
    />
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en-AU" className={`${oswald.variable} ${inter.variable}`}>
      <body className="bg-white text-brand-charcoal antialiased">
        <LocalBusinessJsonLd />
        {children}
      </body>
    </html>
  );
}
